// Generated by CoffeeScript 1.7.1
(function() {
  var HeaderFPT, fs, iconv;

  fs = require('fs');

  iconv = require('iconv-lite');

  HeaderFPT = (function() {
    function HeaderFPT(filename, encoding) {
      this.filename = filename;
      this.encoding = encoding;
      return this;
    }

    HeaderFPT.prototype.parse = function(callback) {
      return fs.readFile("" + this.filename + ".fpt", (function(_this) {
        return function(err, buffer) {
          if (err) {
            throw err;
          }
          _this.nextFreeBlock = (buffer.slice(0, 4)).readInt32BE(0, true);
          _this.memoSingleBlockLength = (buffer.slice(6, 8)).readInt16BE(0, true);
          return callback(_this);
        };
      })(this));
    };

    return HeaderFPT;

  })();

  module.exports = HeaderFPT;

}).call(this);
